In [20]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [21]:
df.head(5)

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [32]:
df.rename(columns={"entity": "Pais", "year": "Anio", "life_expectancy": "Esperanza de vida"}, inplace=True)

In [36]:
df.reset_index(inplace=True)
df.set_index("Pais", inplace=True)

In [37]:
df.head(3)

            code  Anio  life_expectancy_0
Pais
Afghanistan  AFG  1950            28.1563
Afghanistan  AFG  1951            28.5836
Afghanistan  AFG  1952            29.0138

In [40]:
df.reset_index(inplace=True)
df.set_index(["Pais", "Anio"], inplace=True)

In [41]:
df.head(3)

                 code  life_expectancy_0
Pais        Anio
Afghanistan 1950  AFG            28.1563
            1951  AFG            28.5836
            1952  AFG            29.0138

In [44]:
df.reset_index(inplace=True)
df.loc[df["Pais"].str.contains("U", case=False, regex=True)]

                    Pais  Anio code  life_expectancy_0
604             Anguilla  1950  AIA            55.0563
605             Anguilla  1951  AIA            55.5932
606             Anguilla  1952  AIA            56.0813
607             Anguilla  1953  AIA            56.5817
608             Anguilla  1954  AIA            57.0804
...                  ...   ...  ...                ...
21183  Wallis and Futuna  2019  WLF            77.9936
21184  Wallis and Futuna  2020  WLF            78.1637
21185  Wallis and Futuna  2021  WLF            77.4609
21186  Wallis and Futuna  2022  WLF            78.5005
21187  Wallis and Futuna  2023  WLF            78.6286

[7375 rows x 4 columns]

In [45]:
df.loc[df["code"].isnull()]

                                        Pais  Anio code  life_expectancy_0
375                                 Americas  1770  NaN            34.8000
376                                 Americas  1830  NaN            34.8000
377                                 Americas  1850  NaN            35.1000
378                                 Americas  1870  NaN            35.1000
379                                 Americas  1900  NaN            41.0000
...                                      ...   ...  ...                ...
17703  Small Island Developing States (SIDS)  2019  NaN            72.0847
17704  Small Island Developing States (SIDS)  2020  NaN            71.7761
17705  Small Island Developing States (SIDS)  2021  NaN            69.8938
17706  Small Island Developing States (SIDS)  2022  NaN            72.1257
17707  Small Island Developing States (SIDS)  2023  NaN            72.7255

[1348 rows x 4 columns]

In [46]:
df.dropna(subset=["code"], inplace=True)
df.isnull().sum()

Pais                 0
Anio                 0
code                 0
life_expectancy_0    0
dtype: int64

In [52]:
df.rename(columns={"life_expectancy_0": "Esperanza de vida"}, inplace=True)

resultado = (
    df.groupby("Pais")["Esperanza de vida"]
    .mean()
    .sort_values(ascending=True)
)

In [53]:
df.head()

          Pais  Anio code  Esperanza de vida
0  Afghanistan  1950  AFG            28.1563
1  Afghanistan  1951  AFG            28.5836
2  Afghanistan  1952  AFG            29.0138
3  Afghanistan  1953  AFG            29.4521
4  Afghanistan  1954  AFG            29.6975

In [60]:
resultado = df[df["Anio"] == 2020].groupby("Pais")["Esperanza de vida"].mean().sort_values(ascending=False)

In [64]:
print(resultado)

Pais
Monaco                      86.0893
Hong Kong                   84.7073
Japan                       84.6703
Macao                       84.6100
Saint Barthelemy            84.0707
                             ...
Somalia                     57.0948
Lesotho                     55.1325
Chad                        53.0818
Nigeria                     53.0724
Central African Republic    50.5959
Name: Esperanza de vida, Length: 246, dtype: float64